services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"  # Puerto para conexiones MQTT
      - "9001:9001"  # Puerto para WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - LOG_DESTINATION=stdout
      - ALLOW_ANONYMOUS=true
    restart: always

  # Verificar con software MQTT Explorer