services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql

  spring-boot-app:
    build:
      context: ./server
    ports:
      - "${SPRING_PORT}:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_DEVTOOLS_RESTART_STATUS=${SPRING_DEVTOOLS_RESTART_STATUS}
      - SPRING_DEVTOOLS_LIVERELOAD_STATUS=${SPRING_DEVTOOLS_LIVERELOAD_STATUS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_EMAIL_USERNAME=${SPRING_EMAIL_USERNAME}
      - SPRING_EMAIL_PASSWORD=${SPRING_EMAIL_PASSWORD}
      - INFLUXDB_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_INIT_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_INIT_BUCKET}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    volumes:
      - ./server:/app
      - ~/.m2:/root/.m2
    depends_on:
      - influxdb
      - mosquitto
      - mysql

  angular-app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "${ANGULAR_PORT}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - mysql

  influxdb:
    image: influxdb:2.4
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - "${INFLUXDB_PORT}:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    depends_on:
      - mysql

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "${MOSQUITTO_PORT_MQTT}:1883"
      - "${MOSQUITTO_PORT_WEBSOCKETS}:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - LOG_DESTINATION=stdout
      - ALLOW_ANONYMOUS=true
    restart: always

volumes:
  mysql_data:
  influxdb_data:
  grafana_data:
