services:
  #Configuracion servicio MySQL
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpifinal
    volumes:
  # Ejecutar archivo inicial db.sql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  #Configuracion servicio PHPAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root  # Usuario phpMyAdmin
      PMA_PASSWORD: root  # Contraseña phpMyAdmin
    ports:
      - "8081:80"
    depends_on:
      - mysql
  # Configuración servicio Spring Boot
  spring-boot-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server:/app
      - ~/.m2:/root/.m2
    depends_on:
      - influxdb
  # Configuración servicio Angular
  angular-app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - mysql
  # Configuración servicio InfluxDB
  influxdb:
    image: influxdb:2.4
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=grupo10
      - DOCKER_INFLUXDB_INIT_BUCKET=grupo10bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=grupo10token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    depends_on:
      - mysql
  # Configuración servicio Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
volumes:
  mysql_data:
  influxdb_data:
  grafana_data: