services:
  #Configuracion servicio MySQL
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root  # Contrase침a
      MYSQL_DATABASE: tpifinal  # Nombre de la base de datos
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql  # Ejecutar archivo inicial db.sql
      - mysql_data:/var/lib/mysql  # Volumen para persistir datos
    ports:
      - "3307:3306"
  #Configuracion servicio PHPAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root  # Usuario phpMyAdmin
      PMA_PASSWORD: root  # Contrase침a phpMyAdmin
    ports:
      - "8081:80"
    depends_on:
      - mysql
  # Configuraci칩n servicio Spring Boot
  spring-boot-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - ~/.m2:/root/.m2
    depends_on:
      - mysql
  # Configuraci칩n servicio Angular
  angular-app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - mysql
volumes:
  mysql_data: